#!/bin/bash
#### Check for yay ####
ISYAY=/sbin/yay
if [ -f "$ISYAY" ]; then 
    echo -e "yay was located, moving on.\n"
    yay -Suy
else 
    echo -e "yay was not located, please install yay. Exiting script.\n"
    exit 
fi

### Disable wifi powersave mode ###
read -n1 -rep 'Would you like to disable wifi powersave? (y,n)' WIFI
if [[ $WIFI == "Y" || $WIFI == "y" ]]; then
    LOC="/etc/NetworkManager/conf.d/wifi-powersave.conf"
    echo -e "The following has been added to $LOC.\n"
    echo -e "[connection]\nwifi.powersave = 2" | sudo tee -a $LOC
    echo -e "\n"
    echo -e "Restarting NetworkManager service...\n"
    sudo systemctl restart NetworkManager
    sleep 3
fi

### Install all of the above pacakges ####
read -n1 -rep 'Would you like to install the packages? (y,n)' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    yay -S --noconfirm hyprland kitty waybar \
    swaybg swaylock-effects wofi wlogout \
    ttf-jetbrains-mono-nerd noto-fonts-emoji \
    polkit-gnome python-requests starship \
    swappy grim slurp pamixer brightnessctl gvfs \
    bluez bluez-utils lxappearance xfce4-settings \
    dracula-gtk-theme dracula-icons-git xdg-desktop-portal-hyprland

    # Start the bluetooth service
    echo -e "Starting the Bluetooth Service...\n"
    sudo systemctl enable --now bluetooth.service
    sleep 2
    
    # Clean out other portals
    echo -e "Cleaning out conflicting xdg portals...\n"
    yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk
fi

#!/bin/bash

# Prompt user for confirmation
read -n1 -rep 'Would you like to install the packages? (y,n): ' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    echo -e "\nInstalling packages..."

    # Install packages with pacman
    sudo pacman -S --noconfirm --needed \
        kde-frameworks kdelibs kde-gtk-config arc-gtk-theme \
        thunar xorg-setxkbmap swaync jq swaymsg hyprctl hyprlock git base-devel \
        p7zip unzip unrar tar thunar-archive-plugin file-roller gedit \
        xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-qt grim \
        btop htop neofetch

    # Install packages with yay
    yay -S --noconfirm google-chrome swaync clipman joe visual-studio-code-bin

    # Optional: Start and enable the Bluetooth service
    echo -e "\nStarting the Bluetooth service..."
    sudo systemctl enable --now bluetooth.service
    sleep 2

    # Optional: Clean conflicting xdg portals (if relevant)
    echo -e "\nCleaning out conflicting xdg portals..."
    yay -R --noconfirm xdg-desktop-portal-gnome xdg-desktop-portal-gtk

    echo -e "\nInstallation complete!"
else
    echo -e "\nInstallation canceled."
fi

# Prompt user for confirmation
read -n1 -rep 'Would you like to install all the packages? (zathura, gnome-calculator, Calendar, blueman-manager, telegram, discord, skype, youtube-music, obsidian, obs, gimp) (y,n): ' INST
if [[ $INST == "Y" || $INST == "y" ]]; then
    echo -e "\nInstalling packages..."

    # Install packages with pacman
    sudo pacman -S --noconfirm --needed \
        zathura gimp

    # Install packages with yay
    yay -S --noconfirm \
        gnome-calculator gnome-calendar blueman telegram-desktop \
        discord skypeforlinux-stable-bin youtube-music-bin obsidian obs-studio

    echo -e "\nInstallation complete!"
else
    echo -e "\nInstallation canceled."
fi

### Copy Config Files ###
read -n1 -rep 'Would you like to copy config files? (y,n)' CFG
if [[ $CFG == "Y" || $CFG == "y" ]]; then
    echo -e "Copying config files...\n"
    cp -R hypr ~/.config/
    cp -R kitty ~/.config/
    cp -R neofetch ~/.config/
    cp -R ranger ~/.config/
    cp -R swaylock ~/.config/
    cp -R waybar ~/.config/
    cp -R swaync ~/.config/
    cp -R wofi ~/.config/
    cp -R zathura ~/.config/
    cp -R xfce4 ~/.config/
    cp -R applications ~/.local/share/
    cp -R .vscode ~/
    cp -R Kvantum ~/.config/
    
    # Set some files as exacutable 
    chmod +x ~/.config/hypr/xdg-portal-hyprland
    chmod +x ~/.config/waybar/scripts/waybar-wttr.py
fi

### Install teh starship shell ###
read -n1 -rep 'Would you like to install the starship shell? (y,n)' STAR
if [[ $STAR == "Y" || $STAR == "y" ]]; then
    # install the starship shell
    echo -e "Updating .bashrc...\n"
    echo -e '\neval "$(starship init bash)"' >> ~/.bashrc
    echo -e "copying starship config file to ~/.confg ...\n"
    cp starship.toml ~/.config/
fi

### Copy .bashrc and .aliases ###
read -n1 -rep 'Would you like to copy .bashrc and .aliases? (y,n) ' COPY_CONF
if [[ $COPY_CONF == "Y" || $COPY_CONF == "y" ]]; then
    echo -e "Copying .bashrc to home directory...\n"
    cp .bashrc ~/
    echo -e "Copying .aliases to home directory...\n"
    cp .aliases ~/
    echo -e "Files have been successfully copied!"
fi

### Script is done ###
echo -e "Script had completed.\n"
echo -e "You can start Hyprland by typing Hyprland (note the capital H).\n"
read -n1 -rep 'Would you like to start Hyprland now? (y,n)' HYP
if [[ $HYP == "Y" || $HYP == "y" ]]; then
    exec Hyprland
else
    exit
fi
